"use client";
import InnerPage from "../components/InnerPage";

const S = { h2:{ fontSize:20, fontWeight:700, color:"#fff", marginBottom:12, marginTop:32 }, p:{ fontSize:14.5, color:"#9590aa", lineHeight:1.75, marginBottom:12 }, ul:{ paddingLeft:20, marginBottom:12 }, li:{ fontSize:14.5, color:"#9590aa", lineHeight:1.75, marginBottom:6 } };

export default function Terms() {
  return (
    <InnerPage title="Terms of service">
      <p style={{ fontSize:13, color:"#5f5a75", marginBottom:40 }}>Last updated: March 20, 2026</p>

      <p style={S.p}>Welcome to MentionMe. By accessing or using our platform at mentionme.app ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service.</p>

      <h2 style={S.h2}>1. Account registration</h2>
      <p style={S.p}>To use MentionMe, you must create an account and provide accurate, complete information. You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. You must be at least 18 years old to use the Service.</p>

      <h2 style={S.h2}>2. Service description</h2>
      <p style={S.p}>MentionMe is a Generative Engine Optimization (GEO) platform that helps users optimize their online content for citation by AI-powered answer engines. The Service includes GEO audits, AI-powered content generation, multi-platform distribution templates, campaign tracking, and visibility monitoring.</p>

      <h2 style={S.h2}>3. Subscription & billing</h2>
      <p style={S.p}>MentionMe offers paid subscription plans (Starter, Pro, Agency) with monthly and annual billing options. All plans include a 7-day free trial. By subscribing, you authorize us to charge your payment method on a recurring basis. You may cancel at any time, and your access will continue until the end of your current billing period. Refunds are not provided for partial billing periods.</p>

      <h2 style={S.h2}>4. Acceptable use</h2>
      <p style={S.p}>You agree not to use MentionMe to:</p>
      <ul style={S.ul}>
        <li style={S.li}>Generate content that is illegal, defamatory, harassing, or violates any third-party rights</li>
        <li style={S.li}>Create spam, misleading content, or content designed to manipulate AI systems through deceptive means</li>
        <li style={S.li}>Reverse engineer, decompile, or attempt to extract source code from the Service</li>
        <li style={S.li}>Share your account credentials or allow unauthorized access to your account</li>
        <li style={S.li}>Use the Service to compete directly with MentionMe or build a competing product</li>
        <li style={S.li}>Exceed the usage limits of your subscription plan through automated or programmatic means</li>
      </ul>

      <h2 style={S.h2}>5. Content ownership</h2>
      <p style={S.p}>You retain ownership of all input data you provide (brand names, URLs, descriptions). Content generated by MentionMe using AI is licensed to you for your commercial use. You are responsible for reviewing all generated content before publication. MentionMe does not claim ownership over content you create or generate using the platform.</p>

      <h2 style={S.h2}>6. AI-generated content disclaimer</h2>
      <p style={S.p}>Content generated by MentionMe is produced using artificial intelligence and is provided "as is." While we strive for accuracy and quality, AI-generated content may contain errors, inaccuracies, or biases. You are solely responsible for reviewing, editing, and verifying all content before publishing or distributing it. MentionMe does not guarantee that generated content will result in AI citation or increased traffic.</p>

      <h2 style={S.h2}>7. No guaranteed results</h2>
      <p style={S.p}>MentionMe provides tools and strategies for Generative Engine Optimization. We do not guarantee specific results, rankings, traffic levels, or AI citation outcomes. Results vary based on factors outside our control, including AI model updates, market competition, and content quality.</p>

      <h2 style={S.h2}>8. Limitation of liability</h2>
      <p style={S.p}>To the maximum extent permitted by law, MentionMe shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.</p>

      <h2 style={S.h2}>9. Indemnification</h2>
      <p style={S.p}>You agree to indemnify and hold harmless MentionMe, its officers, directors, employees, and agents from any claims, damages, losses, or expenses arising from your use of the Service, your violation of these Terms, or your violation of any third-party rights.</p>

      <h2 style={S.h2}>10. Modifications</h2>
      <p style={S.p}>We reserve the right to modify these Terms at any time. We will notify you of material changes via email or through the platform. Continued use of the Service after changes become effective constitutes acceptance of the revised Terms.</p>

      <h2 style={S.h2}>11. Termination</h2>
      <p style={S.p}>We may suspend or terminate your account if you violate these Terms or engage in conduct that is harmful to other users or the Service. You may terminate your account at any time by contacting us or through your account settings.</p>

      <h2 style={S.h2}>12. Governing law</h2>
      <p style={S.p}>These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which MentionMe operates, without regard to conflict of law principles.</p>

      <h2 style={S.h2}>13. Contact</h2>
      <p style={S.p}>For questions about these Terms, contact us at legal@mentionme.app or use our <a href="/contact" style={{ color:"#ff3c8e" }}>contact form</a>.</p>
    </InnerPage>
  );
}
